###########
# site.title, site.author.name

title:  Strange Case of Dr. Jekyll and Mr. Hyde
author:
  name: Robert Louis Stevenson


########
# more settings

collections:
  chapters:
      output: false

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false
